---
- name: Provision MinIO VM
  hosts: minio_host
  become: true
  
  pre_tasks:
    - name: Install Docker via role (relative path) and pass vars
      import_role:
        name: ../roles/docker     # relative to THIS playbook file
      vars:
        docker_users:
          - "{{ ansible_user | default('ubuntu') }}"

  tasks:
    - name: Ensure minio group exists
      ansible.builtin.group:
        name: "{{ minio_service_group }}"
        system: true

    - name: Ensure minio user exists
      ansible.builtin.user:
        name: "{{ minio_service_user }}"
        group: "{{ minio_service_group }}"
        system: true
        shell: /usr/sbin/nologin
        create_home: false

    - name: Create data directory
      ansible.builtin.file:
        path: "{{ minio_data_dir }}"
        state: directory
        owner: "{{ minio_service_user }}"
        group: "{{ minio_service_group }}"
        mode: "0770"

    - name: Create compose directory
      ansible.builtin.file:
        path: "{{ minio_compose_dir }}"
        state: directory
        mode: "0755"

    - name: Deploy docker-compose.yml
      ansible.builtin.template:
        src: templates/docker-compose.minio.yml.j2
        dest: "{{ minio_compose_dir }}/docker-compose.yml"
        mode: "0644"

    - name: Launch MinIO via Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: "{{ minio_compose_dir }}"
        state: present